print-progress: true
concurrent: 20
check-interval: 30000
timeout: 2000
speed-test-url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z
min-speed: 1024
download-timeout: 10
listen-port: ""
rename-node: false
node-prefix: ""
media-check: false
platforms:
  - openai
  - youtube
  - netflix
  - disney
  - gemini
  - iprisk
keep-success-proxies: false
success-limit: 0
output-dir: ""
enable-web-ui: false
api-key: ""
callback-script: ""
apprise-api-server: ""
recipient-url: [] # Changed to empty list to indicate no recipients
notify-title: "ğŸ”” èŠ‚ç‚¹çŠ¶æ€æ›´æ–°"
sub-store-port: ""
sub-store-path: ""
mihomo-overwrite-url: "http://127.0.0.1:8199/sub/ACL4SSR_Online_Full.yaml"
mihomo-api-url: ""
mihomo-api-secret: ""
save-method: local
webdav-url: "https://example.com/dav/"
webdav-username: "admin"
webdav-password: "admin"
github-gist-id: ""
github-token: ""
github-api-mirror: ""
worker-url: https://example.worker.dev
worker-token: 1234567890
sub-urls-retry: 3
github-proxy: ""
sub-urls:
  - "https://gist.githubusercontent.com/GeBron/a41c2616cff5ea0c4a96e0567d98dbf6/raw/clash.yaml"
